import globalClassNames from "../../@types/style.d";
declare const classNames: typeof globalClassNames & {
  readonly "color-light": "color-light";
  readonly "color-dark": "color-dark";
  readonly "color-primary": "color-primary";
  readonly "color-secondary": "color-secondary";
  readonly "color-info": "color-info";
  readonly "color-danger": "color-danger";
  readonly "color-warning": "color-warning";
  readonly "color-success": "color-success";
  readonly light: "light";
  readonly dark: "dark";
  readonly primary: "primary";
  readonly secondary: "secondary";
  readonly info: "info";
  readonly danger: "danger";
  readonly warning: "warning";
  readonly success: "success";
};
export = classNames;
